server:
  port: 8080

#数据源的配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moven_db?serverTimezone=UTC
    username: root
    password:
  #Spring Data JPA的配置（Spring默认使用hibernate框架）
  jpa:
    hibernate:
      #当ORM的应用层逻辑（O）改变时，数据库也会相应地改变。
      ddl-auto: update
    #当执行数据库操作时，相应的SQL会被控制台打印出来。
    show-sql: true